parameters:
  jobName: ''
  vmImage: ''
  publishBuildArtifactsArtifactName: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: Publish Build Artifacts
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
    DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    configuration: 'Release'
    # buildPlatform: 'Any CPU'
    verbosity: 'normal'
  steps:

  # For better visualization we go through each step 
  # instead of just defining the steps [test, pack].

  - task: PowerShell@2
    displayName: 'Restore'
    inputs:
      filePath: '$(Build.SourcesDirectory)\build.ps1'
      arguments: 'restore'

  - task: PowerShell@2
    displayName: 'Compile'
    inputs:
      filePath: '$(Build.SourcesDirectory)\build.ps1'
      arguments: 'compile --configuration $(configuration) --verbosity $(verbosity)'

  - task: PowerShell@2
    displayName: 'Test'
    inputs:
      filePath: '$(Build.SourcesDirectory)\build.ps1'
      arguments: 'test --configuration $(configuration) --verbosity $(verbosity)'

  - task: PowerShell@2
    displayName: 'Pack'
    inputs:
      filePath: '$(Build.SourcesDirectory)\build.ps1'
      arguments: 'pack --configuration $(configuration) --verbosity $(verbosity)'
      
  - task: CopyFiles@2
    displayName: 'Copy Build Artifacts'
    inputs:
      Contents: $(Build.SourcesDirectory)/obj/packages/*.?(s)nupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      TargetPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: ${{ parameters.publishBuildArtifactsArtifactName }}
      publishLocation: Container